export default {
  PhoneVerification: 'PhoneVerificationScreen',
  Splash: 'SplashScreen',
  Onboarding: 'OnboardingScreen',
  SelectContacts: 'SelectContactsScreen',
  Preview: 'PreviewScreen',
  Main: 'MainScreen',
  Answers: 'AnswersScreen',
  BlockContacts: 'BlockContactsScreen',
  Conversation: 'ConversationScreen',
  Survey: 'SurveyScreen',
  MessageContacts: 'MessageContactsScreen',
  Messages: 'MessagesScreen',
  Report: 'ReportScreen',
  FollowContacts: 'FollowContactsScreen',
  MainStack: 'MainStack',
  FollowContactsStack: 'FollowContactsStack',
  ReportStack: 'ReportStack',
  RequestContactsToAsk: 'RequestContactsToAskScreen',
  RequestToAsk: 'RequestToAskScreen',
  ImportGmailContacts: 'ImportGmailContactsScreen',
  ImportGmailContactsStack: 'ImportGmailContactsStack',
}
