export default {
  Drawer: 'Drawer',
  PhoneVerification: 'PhoneVerificationScreen',
  Splash: 'SplashScreen',
  Onboarding: 'OnboardingScreen',
  SelectContacts: 'SelectContactsScreen',
  Preview: 'PreviewScreen',
  Main: 'MainScreen',
  Answers: 'AnswersScreen',
  BlockContacts: 'BlockContactsScreen',
  Conversation: 'ConversationScreen',
  Survey: 'SurveyScreen',
  MessageContacts: 'MessageContactsScreen',
  Messages: 'MessagesScreen',
  Report: 'ReportScreen',
  FollowContacts: 'FollowContactsScreen',
}
