require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.3'

target 'Berrys' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  # Custom pods
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'FacebookSDK'
  pod 'FacebookSDK/LoginKit'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"

  target 'BerrysTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
