export default [
  {
    id: 1,
    icon: 'opinion',
    name: 'Opinion',
    value: 'Opinion',
    size: 40,
    marginBottom: 10,
    popularQuestions: [
      'Is it OK to have a favorite child?',
      'What do you think of this letter?',
      'What do you think of Cale Gnocchi? Do you like it?',
      'Do you think wearing cloth masks would protect you from COVID?',
      'What do you think of this idea ______ ?',
    ],
  },
  {
    id: 2,
    icon: 'recommendation',
    name: 'Recommen-dation',
    value: 'Recommendation',
    size: 40,
    marginBottom: 10,
    popularQuestions: [
      'Could you recommend a good urologist in New York City?',
      `What's the best restaurant in the area to take someone for a first date?`,
      'Would you write a recommendation letter to your service provider?',
      'Which tampon brand would you recommend to use?',
      'Could you recommend a good psychiatrist to get a help with relationship issues?',
    ],
  },
  {
    id: 3,
    icon: 'advice',
    name: 'Advice',
    value: 'Advice',
    size: 40,
    marginBottom: 10,
    popularQuestions: [
      'What advice would you give to a younger self?',
      'Would you break up with your bf if you have the same core values, but argue on small things often?',
      `What's the best first-date advice you can give to a guy?`,
      `What to do if you're attracted to the same sex?`,
      `Is it a good idea for businesses "to fake it till you make it"?`,
    ],
  },
  {
    id: 4,
    icon: 'profile',
    name: 'About Someone',
    value: 'About Someone',
    size: 28,
    marginBottom: 10,
    popularQuestions: [
      'What do you think of Nick Dawson?',
      'Is Joe Johnson really enthusiastic about Tech?',
      `What do you think is Jose Lopez's strongest point in professional life?`,
      'Is Robert a loyal employee?',
      'Do you think Susan is a good manager?',
    ],
  },
  // {
  //   id: 5,
  //   icon: 'about-something',
  //   name: 'About Something',
  //   value: 'About Something',
  // },
  {
    id: 6,
    icon: 'how-to',
    name: 'How-to',
    value: 'How-to',
    size: 50,
    marginBottom: 0,
    popularQuestions: [
      'How to pretend you like a gift?',
      `How to act around the girl who has a crush on you, but you don't like her?`,
      'How to sell my car?',
      'How do you tell a guy you like that you have a crush on him?',
      `How to get a job, if you don't have a work experience?`,
    ],
  },
  {
    id: 8,
    icon: 'taboo',
    name: 'Taboo',
    value: 'Taboo',
    size: 30,
    marginBottom: 10,
    popularQuestions: [
      `What's your guilty pleasure?`,
      'Have you ever peed on your bed as a grown up?',
      'Do mature women in Bay Area prefer guys to be groomed down there?',
      'What would you do if you find out your partner is cheating on you?',
      'Have you ever had an orgasm while being asleep?',
    ],
  },
  {
    id: 9,
    icon: 'political',
    name: 'Political',
    value: 'Political',
    size: 30,
    marginBottom: 10,
    popularQuestions: [
      `What do you think of COVID19? Do you think it's a political game?`,
      'Should Trump be elected for a second term?',
      'Democrats or Republicans?',
      'Do you think our world is ruled by a very few families?',
      'Why does it take so long to do construction on roads? Is it because of corruption?',
    ],
  },
  {
    id: 10,
    icon: 'financial',
    name: 'Financial',
    value: 'Financial',
    size: 30,
    marginBottom: 10,
    popularQuestions: [
      'Would you lend your family friend $1k for a month?',
      'How much does an average barber make in San Francisco?',
      'When is the best time to leave the company to get the bonuses and stock option?',
      'Where would you invest $30k now to get the most return for your investment, within a year?',
      `What's is the most promising area to buy a home now?`,
    ],
  },
  {
    id: 7,
    icon: 'others',
    name: 'Other',
    value: 'Other',
    size: 40,
    marginBottom: 0,
    popularQuestions: [
      'If you were home by yourself all day, what would you do?',
      'Have you ever peed yourself?',
      'How often do you wash your undergarments?',
      'What is the most illegal thing you have ever done?',
      'If you could suddenly become invisible, what would you do?',
    ],
  },
  {
    id: 11,
    icon: 'checkmark',
    name: 'Self Growth',
    value: 'Self Growth',
    size: 40,
    marginBottom: 10,
    popularQuestions: [
      /* 'If you were home by yourself all day, what would you do?',
      'Have you ever peed yourself?',
      'How often do you wash your undergarments?',
      'What is the most illegal thing you have ever done?',
      'If you could suddenly become invisible, what would you do?', */
    ],
  },
  {
    id: 12,
    icon: 'chat1',
    name: 'Mental Health',
    value: 'Mental Health',
    size: 28,
    marginBottom: 10,
    popularQuestions: [
      /* 'If you were home by yourself all day, what would you do?',
      'Have you ever peed yourself?',
      'How often do you wash your undergarments?',
      'What is the most illegal thing you have ever done?',
      'If you could suddenly become invisible, what would you do?', */
    ],
  },
  {
    id: 13,
    icon: 'group-senior',
    name: 'Family',
    value: 'Family',
    size: 28,
    marginBottom: 10,
    popularQuestions: [
      /* 'If you were home by yourself all day, what would you do?',
      'Have you ever peed yourself?',
      'How often do you wash your undergarments?',
      'What is the most illegal thing you have ever done?',
      'If you could suddenly become invisible, what would you do?', */
    ],
  },
]
